name: Continuous Integration

on:
  pull_request:
  push:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1
        
      - name: Build project
        run: sbt test

      - name: Compress target directories
        run: tar cf targets.tar backend/target

      - name: Upload target directories
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: targets.tar

