name: Continuous Integration

on:
  pull_request:
  push:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        scala-version: [Versions.scala]
        java-version: [8, 11, 17]
      
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Scala v${{ matrix.scala-version }} with Java v${{ matrix.java-version }} and Node v${{ matrix.node-version }}
        uses: japgolly/setup-everything-scala@v3.1
        with:
          java-version: temurin:${{ matrix.java-version }}
          node-version: ${{ matrix.node-version }}

      - name: install npm deps
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
        
      - name: Build project
        run: sbt++field ${{ matrix.scala-version }} test

      - name: Compress target directories
        run: tar cf targets.tar backend/target frontend/target

      - name: Upload target directories
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: targets.tar

